const { default: mongoose } = require("mongoose");
const Event = require("../../models/Event");
const EventSession = require("../../models/EventSession");
const QueryBuilder = require("../../services/queryBuilder");
const catchAsync = require("../../utils/catchAsync");
const { successRes } = require("../../utils/responseFormatter");
const AppError = require("../../utils/AppError");
const GatekeeperScan = require("../../models/GatekeeperScan");
const ENVIRONMENT = require("../../config/env.js");
const { isValidId } = require("../../helper/productHelper.js");
const TicketBooking = require("../../models/TicketBooking.js");

const generateTicketFromAdminSide = catchAsync(async (req, res, next) => {
    let {
        sessionId,
        eventId,
        quantity,
        isVipTicket = false,
        isValidForAllDays = false,
        ticketName
    } = req.body;

    // 🔹 Validate IDs
    if (!isValidId(sessionId)) return next(new AppError("Invalid session id", 400));
    if (!isValidId(eventId)) return next(new AppError("Invalid event id", 400));

    // 🔹 Validate quantity
    if (!quantity) return next(new AppError("Quantity is required", 400));
    quantity = parseInt(quantity, 10);
    if (isNaN(quantity) || quantity <= 0) {
        return next(new AppError("Quantity must be a positive integer", 400));
    }

    // 🔹 Limit per booking (Admin override allowed via env)
    const limitPerBooking = parseInt(process.env.MAX_TICKETS_PER_BOOKING || 20, 10);
    if (quantity > limitPerBooking) {
        return next(new AppError(`You can book a maximum of ${limitPerBooking} tickets at a time`, 400));
    }

    // 🔹 Validate session
    const sessionData = await EventSession.findOne({
        _id: sessionId,
        event: eventId,
        isDeleted: false
    });
    if (!sessionData) return next(new AppError("Event session not found", 404));

    // 🔹 Validate event
    const eventData = await Event.findOne({ _id: eventId, isDeleted: false });
    if (!eventData) return next(new AppError("Event not found", 404));

    //Expiry Check
    const today = new Date();
    today.setHours(0, 0, 0, 0); // reset time to midnight

    const sessionDate = new Date(sessionData.date);
    sessionDate.setHours(0, 0, 0, 0);
    console.log(sessionDate, "sessionDate", today, "today")
    if (sessionDate < today) {
        return next(new AppError("This event session has already expired", 400));
    }


    // 🔹 Price calculation
    const pricePerTicket = sessionData.pricePerTicket || eventData.price || 0;
    const totalAmount = pricePerTicket * quantity;

    // 🔹 Final flag for validity
    const finalIsValidForAllDays = isVipTicket ? true : !!isValidForAllDays;
    console.log("finalIsValidForAllDays", finalIsValidForAllDays)
    // 🔹 Attendee details (condition based)
    const attendeeName = isVipTicket
        ? `${ticketName}`
        : isValidForAllDays
            ? `${ticketName}`
            : `${ticketName}`;

    const attendeeDetails = Array.from({ length: 1 }, (_, i) => ({
        name: `${attendeeName}`,
        phone: ""
    }));

    // 🔹 Capacity check (only for normal non-allDay tickets)
    if (!isVipTicket && !finalIsValidForAllDays) {
        if (sessionData.remainingCapacity < quantity) {
            return next(new AppError("Not enough tickets available", 400));
        }
    }

    // 🔹 Create booking (without payment)
    const booking = await TicketBooking.create({
        user: req.user._id, // Admin ID
        eventSession: sessionId,
        event: eventId,
        quantity,
        attendeeDetails,
        pricePerTicket,
        totalAmount,
        currency: "INR",
        paymentMethod: "razorpay", // keeping enum value same
        paymentStatus: "paid",     // mark as paid since admin generated
        ticketStatus: "pending",   // can later be confirmed
        tickets: [],
        notes: "Admin generated booking",
        generatedBy: "admin",
        isVipTicket,
        validForAllDays: finalIsValidForAllDays
    });

    // 🔹 Update session capacity only if applicable
    if (!isVipTicket && !finalIsValidForAllDays) {
        sessionData.remainingCapacity -= quantity;
        await sessionData.save();
    }

    return successRes(
        res,
        201,
        true,
        "Tickets generated by admin successfully",
        { bookingId: booking._id }
    );
});

// const getAllGeneratedByTicketId = catchAsync(async (req, res, next) => {
//     const { eventId, sessionId, isVip, validForAllDays, page = 1, limit = 10, ticketStatus = "confirmed" } = req.query;

//     if (!eventId) return next(new AppError("eventId is required", 400));
//     if (!isValidId(eventId)) return next(new AppError("Invalid event id", 400));
//     if (sessionId && !isValidId(sessionId)) return next(new AppError("Invalid session id", 400));
//     if (ticketStatus && !['pending', 'confirmed', 'failed'].includes(ticketStatus)) {
//         return next(new AppError('Invalid status value', 400));
//     }

//     const pageNum = parseInt(page);
//     const pageSize = parseInt(limit);

//     // -------- Build Match Object --------
//     const matchBooking = {
//         event: new mongoose.Types.ObjectId(eventId),
//         ticketStatus
//     };
//     if (sessionId) matchBooking.eventSession = new mongoose.Types.ObjectId(sessionId);

//     const orGeneratedBy = [
//         { generatedBy: "admin" },
//         { generatedBy: { $exists: false } }
//     ];

//     // -------- Ticket Filter --------
//     const ticketFilter = {};
//     if (typeof isVip !== "undefined") ticketFilter.isVipTicket = isVip === "true";
//     if (typeof validForAllDays !== "undefined") ticketFilter.validForAllDays = validForAllDays === "true";

//     const pipeline = [
//         { $match: matchBooking },
//         { $match: { $or: orGeneratedBy } },
//         {
//             $addFields: {
//                 tickets: {
//                     $filter: {
//                         input: "$tickets",
//                         as: "ticket",
//                         cond: {
//                             $and: Object.entries(ticketFilter).map(([key, value]) => ({ $eq: [`$$ticket.${key}`, value] }))
//                         }
//                     }
//                 }
//             }
//         },
//         // Lookup Event and Session
//         {
//             $lookup: {
//                 from: "events",
//                 localField: "event",
//                 foreignField: "_id",
//                 as: "event"
//             }
//         },
//         { $unwind: { path: "$event", preserveNullAndEmptyArrays: true } },
//         {
//             $lookup: {
//                 from: "eventsessions",
//                 localField: "eventSession",
//                 foreignField: "_id",
//                 as: "session"
//             }
//         },
//         { $unwind: { path: "$session", preserveNullAndEmptyArrays: true } },
//         { $sort: { createdAt: -1 } },
//         { $skip: (pageNum - 1) * pageSize },
//         { $limit: pageSize }
//     ];

//     const tickets = await TicketBooking.aggregate(pipeline);

//     // Count total bookings (for pagination)
//     const countPipeline = [
//         { $match: matchBooking },
//         { $match: { $or: orGeneratedBy } }
//     ];
//     const countResult = await TicketBooking.aggregate(countPipeline);
//     const totalTickets = countResult.length;
//     const totalPages = Math.ceil(totalTickets / pageSize);

//     return successRes(res, 200, true, "Tickets fetched successfully", {
//         totalTickets,
//         totalPages,
//         currentPage: pageNum,
//         pageSize,
//         tickets
//     });
// });

const getAllGeneratedByTicketId = catchAsync(async (req, res, next) => {
    let { eventId, sessionId, isVip, validForAllDays, page = 1, limit = 10, ticketStatus = "confirmed", search } = req.query;

    if (!eventId) return next(new AppError("eventId is required", 400));
    if (!isValidId(eventId)) return next(new AppError("Invalid event id", 400));
    if (sessionId && !isValidId(sessionId)) return next(new AppError("Invalid session id", 400));
    if (ticketStatus && !['pending', 'confirmed', 'failed'].includes(ticketStatus)) {
        return next(new AppError('Invalid status value', 400));
    }
    if (!search) search = ""

    const pageNum = parseInt(page);
    const pageSize = parseInt(limit);

    // -------- Build Root Match Object --------
    const matchBooking = {
        event: new mongoose.Types.ObjectId(eventId),
        ticketStatus,
        //search using attendee name inside root
        $or: [
            { "attendeeDetails.name": { $regex: search, $options: "i" } },

        ]
    };
    if (sessionId) matchBooking.eventSession = new mongoose.Types.ObjectId(sessionId);

    if (typeof isVip !== "undefined") matchBooking.isVipTicket = isVip === "true";
    if (typeof validForAllDays !== "undefined") matchBooking.validForAllDays = validForAllDays === "true";

    const orGeneratedBy = [
        { generatedBy: "admin" },
        { generatedBy: { $exists: false } }
    ];

    // -------- Aggregation Pipeline --------
    const pipeline = [
        { $match: { $and: [matchBooking, { $or: orGeneratedBy }] } },
        // Lookup Event
        {
            $lookup: {
                from: "events",
                localField: "event",
                foreignField: "_id",
                as: "event"
            }
        },
        { $unwind: { path: "$event", preserveNullAndEmptyArrays: true } },
        // Lookup Session
        {
            $lookup: {
                from: "eventsessions",
                localField: "eventSession",
                foreignField: "_id",
                as: "session"
            }
        },
        { $unwind: { path: "$session", preserveNullAndEmptyArrays: true } },
        { $sort: { createdAt: -1 } },
        { $skip: (pageNum - 1) * pageSize },
        { $limit: pageSize }
    ];

    const tickets = await TicketBooking.aggregate(pipeline);

    // Count total bookings (for pagination)
    const totalTickets = await TicketBooking.countDocuments({ $and: [matchBooking, { $or: orGeneratedBy }] });
    const totalPages = Math.ceil(totalTickets / pageSize);

    return successRes(res, 200, true, "Tickets fetched successfully", {
        totalTickets,
        totalPages,
        currentPage: pageNum,
        pageSize,
        tickets
    });
});


const getTicketsBySessionId = catchAsync(async (req, res, next) => {
    let { sessionId, page = 1, limit = 10, ticketStatus } = req.query;

    if (!isValidId(sessionId)) return next(new AppError('Invalid session id', 400));

    if (ticketStatus && !['pending', 'confirmed', 'failed'].includes(ticketStatus)) {
        return next(new AppError('Invalid status value', 400));
    }

    if (!ticketStatus) ticketStatus = "confirmed";

    // Count total tickets
    const countBuilder = new QueryBuilder(TicketBooking);
    const totalTickets = await countBuilder
        .filter({
            eventSession: new mongoose.Types.ObjectId(sessionId),
            ticketStatus,
            $or: [
                { generatedBy: "user" },
                { generatedBy: { $exists: false } } // agar field hi nahi hai
            ]
        })
        .count();

    // Fetch paginated tickets
    let qb = new QueryBuilder(TicketBooking);
    const tickets = await qb.aggregate([
        {
            $match: {
                eventSession: new mongoose.Types.ObjectId(sessionId),
                ticketStatus,
                $or: [
                    { generatedBy: "user" },
                    { generatedBy: { $exists: false } }
                ]
            },
        },
        {
            $lookup: {
                from: "eventsessions",
                localField: "eventSession",
                foreignField: "_id",
                as: "eventSessionDetails",
            },
        },
        { $unwind: "$eventSessionDetails" },
        {
            $lookup: {
                from: "events",
                localField: "eventSessionDetails.event",
                foreignField: "_id",
                as: "eventDetails",
            },
        },
        {
            $lookup: {
                from: "users",
                localField: "user",
                foreignField: "_id",
                as: "userDetails",
            },
        },
        { $unwind: "$userDetails" },
        { $sort: { createdAt: -1 } },
        { $skip: (parseInt(page, 10) - 1) * parseInt(limit, 10) },
        { $limit: parseInt(limit, 10) },
    ]).exec();

    return successRes(res, 200, true, "Tickets fetched successfully", {
        total: totalTickets,
        page: parseInt(page, 10),
        limit: parseInt(limit, 10),
        data: tickets
    });
});


const getTicketById = catchAsync(async (req, res, next) => {
    const ticketId = req.query.ticketId;

    if (!isValidId(ticketId)) {
        return next(new AppError('Invalid ticket id', 400));
    }

    const qb = new QueryBuilder(TicketBooking);
    const ticket = await qb
        .filter({ _id: new mongoose.Types.ObjectId(ticketId) })
        .populate("user", "-password") // Adjust fields as needed
        .exec();

    if (!ticket) {
        return next(new AppError('Ticket not found', 404));
    }

    return successRes(res, 200, true, "Ticket fetched successfully", ticket);
});


module.exports = {
    getTicketsBySessionId,
    getTicketById,
    generateTicketFromAdminSide,
    getAllGeneratedByTicketId
}